#!/usr/bin/env bash
#install nginx on a server

sudo apt update -y
sudo apt upgrade -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service ngnix restart
