#!/usr/bin/env bash
#configure the nginx server so that /redirect_me is redirecting to another page

sudo apt update -y
sudo apt upgrade -y
sudo apt-get install nginx -y
sudo chown -R "$USER:$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/location / {/location \/redirect_me {\n\t\treturn 301 www.google.com;/g" /etc/nginx/sites-available/default
sudo service nginx restart
