#!/usr/bin/env bash
#install nginx to the server

sudo apt-get update -y
sudo apt-get install -y nginx
sudo chown "$USER":"$USER" /var/www/
sudo chmod -R 777 /var/www/
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo chmod -R 777 /usr/share/nginx/html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sudo sed -i "57i add_header  X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx start

