#!/usr/bin/env bash
#install and cofigure HAproxy on my server

sudo apt-get update -y
sudo apt-get install haproxy=2.0.\* -y
sudo sed -i "$ a\frontend myfrontend\n\tbind 0.0.0.0:80\n\tdefault_backend myservers" /etc/haproxy/haproxy.cfg

sudo sed -i "$ a\backend myservers\n\tserver 285861-web-01 54.236.25.152\n\tserver 285861-web-02 100.26.17.86" /etc/haproxy/haproxy.cfh

sudo services haproxy restart
