#!/usr/bin/env bash
#create the file /var/run/myscript.pd containing its PID
#displays "To infinity and beyon" indefinitely"
#displays "I hate the kill command" when receiving a SIGTERM signal
#displays "Y U no love me?!" when receiveing a SIGINT signal
#deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT and SIGTERM signal

trap 'echo "I hate the kill command"; sudo rm $file; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm $file; exit' SIGQUIT

file="/var/run/myscript.pid"
sudo touch $file
sudo chmod 777 $file
echo "$$" > $file
while true
do
	echo "To infinity and beyond"
	sleep 2
done
