#!/usr/bin/env bash
#displays numbers from 1 to 100.
#displays FizzBuzz when the number is a multiple of 3 and 5
#displays Fizz when the number is mulitiple of 3
#displays Buzz when the number is a mulitple of 5
#otherwise,  displays the number

a=1
while [ $a -le 100 ]
do
	if [ [$(($a % 3)) -eq 0 ] -a [ $(($a % 5)) -eq 0 ] ]
	then
		echo "FizzBuzz"
	elif [ $(($a % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $(($a % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo $a
	fi
	a=$(($a + 1))
done
