#!/usr/bin/env bash
#extract the username, group_id and home)directory and cmd/shell
# from the /etc/passwd file and use it to form a story

while read -r line
do
	IFS=:
	echo "The user $line is part of the gang, lives in and rides.'s place is protected by the passcode , more info about the user here:"
done < /etc/passwd
