#!/usr/bin/env bash
#extract the username, group_id and home)directory and cmd/shell
# from the /etc/passwd file and use it to form a story

while read -r line
do
	IFS=:
	set "$line"
	echo "The user $1 is part of the $4 gang, lives in $6 and rides $7. $3's place is protected by the passcode $2, more info about the user here: $5"
done < /etc/passwd
