#!/usr/bin/env bash
#loops 10 times
#displays bad luck for the 4th loop iteration
#displays good luch for the 8th loop iteration
#displasy Best School for the other iterations
a=1
while [ $a -le 10 ]
do
	if [ $a -eq 4 ]
	then
		echo "bad luck"
	elif [ $a -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	a=$((a + 1))
done
