#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:
#displays hours from 0 to 12
#displays minutes from 1 to 59

a=0
while [ $a -le 12 ]
do
	echo "Hour: $a"
	b=1
	while [ $b -lt 60 ]
	do
		echo $b
		b=$((b + 1))
	done
	a=$((a + 1))
done
