#!/usr/bin/env bash
#displays the content of the current directory
#in a list format
#where only the part of the name after dash is displayed
for content in $(find ./ | cut -d - -f 2) 
do
	echo "$content"
done
