#!/usr/bin/bash

sudo apt update && sudo apt upgrade -y

sudo apt-get install ufw -y

sudo ufw allow proto tcp from any to any port 22

sudo ufw enable

sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
